var topNav='';
topNav+='<header>';
topNav+='	  <div class="top-blue-nav">'; 
topNav+='		<!--Primary Navigation Menu Start-->';
topNav+='<div class="container">';
topNav+='<div class="primary-nav">';
topNav+='    <nav>';
topNav+='      <ul>';
topNav+='<li><a href="http://www.capgemini.com/about-capgemini" TARGET="_NEW"><img src="images/about-icon.png" width="20" height="20" alt=""/> About Us</a></li>';
topNav+='        <li><a href="http://www.in.capgemini.com/contact-capgemini" TARGET="_NEW"><img src="images/contact-icon.png" width="20" height="20" alt=""/> Contact Us</a></li>';
topNav+='      </ul>';
topNav+='    </nav>';
topNav+='  </div>';
topNav+='  <div class="welcome">';
topNav+='    <h5>&nbsp;</h5>';
topNav+='  </div>';
topNav+='  <div class="clearfloat">&nbsp;</div>';
topNav+='</div>';
topNav+='<!--Primary Navigation Menu Ends-->'; 
topNav+='</div>';
topNav+='<div class="navigation">';
topNav+='<div class="container">';
topNav+='  <div class="logo"> ';
topNav+='    <!--logo Start--> ';
topNav+='    <img src="images/logo-cap.jpg" width="197" height="48" alt=""/>'; 
topNav+='    <!--logo Ends--> ';
topNav+='  </div>';
topNav+='  <div class="clearfloat">&nbsp;</div>';
topNav+='</div>';
topNav+='</div>';
topNav+='<div class="title-band">';
topNav+='<div class="container">';
topNav+='  <div class="title">';
topNav+='    <h3>TDG Central</h3>';
topNav+='  </div>';
topNav+='  <div class="clearfloat">&nbsp;</div>';
topNav+='</div>';
topNav+='</div>';
topNav+='</header>';
document.write(topNav);